name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  SwiftActions:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Toolchain
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: sudo apt-get install sqlite3 libsqlite3-dev

    - name: Swift Build
      uses: SwiftActions/SwiftBuild@main

    - name: Swift Test
      uses: SwiftActions/SwiftTest@main
      