name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Build (macOS)
      run: swift build -v
    - name: Run tests
      run: swift test -v
  
  ubuntu-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build (Ubuntu)
      run: swift build -v
    - name: Run tests
      run: swift test -v
